#!/bin/sh

rtt=$(ping -c 10 74.125.226.131 | grep rtt | grep -o '[0-9]\+\.[0-9]\+' | sed -n 2p)
if [ ! -z $rtt ] 
then
	int=$(printf '%.0f\n' $rtt)
	if [ $int -gt 150 ]
	then
		echo "PNG: <fc=#FF0000>$rtt</fc> ms"
	elif [ $int -gt 100 ]
	then
		echo "PNG: <fc=#FFFF00>$rtt</fc> ms"
	else
		echo "PNG: <fc=#00FF00>$rtt</fc> ms"
	fi
else
	echo "PNG: <fc=#FF0000>∞</fc> ms"
fi

exit 0
