#!/bin/sh

rtt=$(ping -c 2 192.168.0.1 | grep rtt | grep -o '[0-9]\+\.[0-9]\+' | sed -n 2p)
if [ ! -z $rtt ] 
then
	int=$(printf '%.0f\n' $rtt)
	if [ $int -gt 150 ]
	then
		echo "PNG: <fc=#FF0000>$int</fc> ms"
	elif [ $int -gt 100 ]
	then
		echo "PNG: <fc=#FFFF00>$int</fc> ms"
	else
		echo "PNG: <fc=#00FF00>$int</fc> ms"
	fi
else
	echo "PNG: <fc=#FF0000>∞</fc> ms"
fi

exit 0
