#!/bin/sh

rtt="`yaourt -Qu | wc -l`"
int=$(printf '%.0f\n' $rtt)
if [ $int -gt 150 ]
then
	echo "UPD: <fc=#FF0000>$rtt</fc>"
elif [ $int -gt 100 ]
then
	echo "UPD: <fc=#FFFF00>$rtt</fc>"
else
	echo "UPD: <fc=#00FF00>$rtt</fc>"
fi

exit 0
